apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-ziy1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mramdani-tenant/partner-catalog-3/partner-catalog-ziy1@sha256:4cf9427ababd58d7b3d8f211986d65a23afa20a94a15554c9ef23dac4a4c3e57
        name: my-java-springboot
        resources: {}
status: {}
